theme: jekyll-theme-slate
title: ePortfolio - Justin Nelson
description: This ePortfolio consists of a code review and three enhancements applied to an Android application to showcase relevant skills in the Computer Science industry.